// prisma/seed/stores.js
// All retailers we track. Affiliate fields filled in later when partner accounts are approved.

const STORES = [
  {
    id: 'apple',
    nombre: 'Apple Store',
    logo: '🍎',
    url: 'https://www.apple.com/es',
    badge: 'OFICIAL',
    country: 'ES',
    language: 'es',
    currency: 'EUR',
    shippingToES: 0,
    shippingDays: 1,
    freeShippingFrom: 0,
    // Apple closed direct affiliate in 2020 — only via Awin now
    affiliateProvider: null,    // 'awin' once approved
    affiliateId: null,
    affiliateTemplate: null,
    commissionPct: null,
    delay: 2000,
    enabled: true,
    scraperType: 'selenium',
  },
  {
    id: 'amazon',
    nombre: 'Amazon España',
    logo: '📦',
    url: 'https://www.amazon.es',
    badge: 'TOP',
    country: 'ES',
    language: 'es',
    currency: 'EUR',
    shippingToES: 0,
    shippingDays: 2,
    freeShippingFrom: 29,
    // Amazon Afiliados — placeholder, fill once approved
    affiliateProvider: 'amazon',
    affiliateId: null,           // e.g. 'manzanaes-21'
    affiliateTemplate: '{url}?tag={affId}',
    commissionPct: 3,
    delay: 1500,
    enabled: true,
    scraperType: 'selenium',
  },
  {
    id: 'mediamarkt',
    nombre: 'MediaMarkt',
    logo: '🛒',
    url: 'https://www.mediamarkt.es',
    badge: '',
    country: 'ES',
    language: 'es',
    currency: 'EUR',
    shippingToES: 0,
    shippingDays: 3,
    freeShippingFrom: 30,
    affiliateProvider: 'awin',
    affiliateId: null,           // e.g. '123456'
    affiliateTemplate: 'https://www.awin1.com/cread.php?awinmid=AWINMID&awinaffid={affId}&p={url}',
    commissionPct: 4,
    delay: 1500,
    enabled: true,
    scraperType: 'selenium',
  },
  {
    id: 'pccomp',
    nombre: 'PcComponentes',
    logo: '💻',
    url: 'https://www.pccomponentes.com',
    badge: '',
    country: 'ES',
    language: 'es',
    currency: 'EUR',
    shippingToES: 0,
    shippingDays: 2,
    freeShippingFrom: 50,
    affiliateProvider: 'tradedoubler',
    affiliateId: null,
    affiliateTemplate: 'https://clk.tradedoubler.com/click?p=PROGRAMID&a={affId}&url={url}',
    commissionPct: 3,
    delay: 1500,
    enabled: true,
    scraperType: 'selenium',
  },
  {
    id: 'fnac',
    nombre: 'Fnac',
    logo: '📚',
    url: 'https://www.fnac.es',
    badge: '',
    country: 'ES',
    language: 'es',
    currency: 'EUR',
    shippingToES: 0,
    shippingDays: 3,
    freeShippingFrom: 25,
    affiliateProvider: 'awin',
    affiliateId: null,
    affiliateTemplate: 'https://www.awin1.com/cread.php?awinmid=AWINMID&awinaffid={affId}&p={url}',
    commissionPct: 4,
    delay: 1500,
    enabled: true,
    scraperType: 'selenium',
  },
  {
    id: 'elcorte',
    nombre: 'El Corte Inglés',
    logo: '🏬',
    url: 'https://www.elcorteingles.es',
    badge: '',
    country: 'ES',
    language: 'es',
    currency: 'EUR',
    shippingToES: 0,
    shippingDays: 3,
    freeShippingFrom: 0,
    affiliateProvider: 'awin',
    affiliateId: null,
    affiliateTemplate: 'https://www.awin1.com/cread.php?awinmid=AWINMID&awinaffid={affId}&p={url}',
    commissionPct: 5,
    delay: 1500,
    enabled: true,
    scraperType: 'selenium',
  },
  {
    id: 'worten',
    nombre: 'Worten',
    logo: '🟢',
    url: 'https://www.worten.es',
    badge: '',
    country: 'ES',
    language: 'es',
    currency: 'EUR',
    shippingToES: 0,
    shippingDays: 3,
    freeShippingFrom: 30,
    affiliateProvider: 'tradedoubler',
    affiliateId: null,
    affiliateTemplate: 'https://clk.tradedoubler.com/click?p=PROGRAMID&a={affId}&url={url}',
    commissionPct: 3,
    delay: 1500,
    enabled: true,
    scraperType: 'selenium',
  },
  {
    id: 'istore',
    nombre: 'iStore (K-tuin)',
    logo: '🍏',
    url: 'https://www.k-tuin.com',
    badge: '',
    country: 'ES',
    language: 'es',
    currency: 'EUR',
    shippingToES: 0,
    shippingDays: 2,
    freeShippingFrom: 0,
    affiliateProvider: null,    // K-tuin doesn't have public affiliate yet
    affiliateId: null,
    affiliateTemplate: null,
    commissionPct: null,
    delay: 1500,
    enabled: true,
    scraperType: 'selenium',
  },
];

module.exports = STORES;
