export const TIENDAS = [
  { id:"apple",      nombre:"Apple Store",    logo:"🍎", url:"https://www.apple.com/es/shop/",      badge:"OFICIAL", delay:900  },
  { id:"mediamarkt", nombre:"MediaMarkt",      logo:"📺", url:"https://www.mediamarkt.es/",          badge:"TOP",     delay:1400 },
  { id:"pccomp",     nombre:"PcComponentes",   logo:"💻", url:"https://www.pccomponentes.com/",      badge:"TECH",    delay:1100 },
  { id:"fnac",       nombre:"Fnac",            logo:"📦", url:"https://www.fnac.es/",                badge:"",        delay:1600 },
  { id:"elcorte",    nombre:"El Corte Inglés", logo:"🏬", url:"https://www.elcorteingles.es/",       badge:"",        delay:2000 },
  { id:"amazon",     nombre:"Amazon.es",       logo:"🛒", url:"https://www.amazon.es/s?k=apple",     badge:"OFERTA",  delay:800  },
  { id:"worten",     nombre:"Worten",          logo:"🔌", url:"https://www.worten.es/",              badge:"",        delay:1300 },
  { id:"istore",     nombre:"iStore",          logo:"🍏", url:"https://www.istore.es/",              badge:"PREMIUM", delay:1000 },
];

export const CATS_NAV = [
  { id:"all",        label:"Todo",         icon:"◈" },
  { id:"iphone",     label:"iPhone",       icon:"📱" },
  { id:"mac",        label:"Mac",          icon:"💻" },
  { id:"ipad",       label:"iPad",         icon:"⬛" },
  { id:"watch",      label:"Apple Watch",  icon:"⌚" },
  { id:"airpods",    label:"AirPods",      icon:"🎧" },
  { id:"accesorios", label:"Accesorios",   icon:"🔌" },
];

export const ESTADOS_BU = ["Excelente","Muy bueno","Bueno","Aceptable"];

export const PRODUCTOS = [
  {
    id:1, nombre:"iPhone 16 Pro 256 GB", cat:"iphone", emoji:"📱", rating:4.9, tag:"Novedad",
    fotos:["#1a1a2e","#16213e","#0f3460","#533483"],
    fotoLabels:["Titanio Negro","Titanio Blanco","Titanio Natural","Titanio Desierto"],
    specs:{ Pantalla:"6.3″ Super Retina XDR OLED", Chip:"A18 Pro", Cámara:"48MP + 48MP + 12MP", Batería:"Hasta 27h vídeo", Almacenamiento:"256 GB", "5G":"Sí", "Face ID":"Sí", Peso:"199 g" },
    desc:"El iPhone más avanzado con chip A18 Pro, cámara de 48MP con zoom óptico 5x y pantalla Always-On ProMotion de 120Hz.",
    reseñas:[
      { fuente:"Xataka",    nota:9.2, texto:"La mejor cámara en un iPhone. El A18 Pro marca diferencia en rendimiento.", fecha:"Oct 2024" },
      { fuente:"El Mundo",  nota:8.9, texto:"Diseño en titanio elegante y duradera. La batería ha mejorado notablemente.", fecha:"Oct 2024" },
      { fuente:"Tudespues", nota:9.0, texto:"Foto y vídeo de nivel profesional. Vale cada euro si usas la cámara a diario.", fecha:"Nov 2024" },
    ],
    historial:[{m:"Ene",p:1289},{m:"Feb",p:1260},{m:"Mar",p:1245},{m:"Abr",p:1229},{m:"May",p:1199},{m:"Jun",p:1185}],
    precios:{ apple:1229, mediamarkt:1219, pccomp:1199, amazon:1185, elcorte:1229, fnac:1215, worten:1209, istore:1229 },
  },
  {
    id:2, nombre:"MacBook Air M3 13″", cat:"mac", emoji:"💻", rating:4.8, tag:"Más vendido",
    fotos:["#1c1c1e","#2c2c2e","#3a3a3c","#48484a"],
    fotoLabels:["Medianoche","Gris Espacial","Plata","Luz Estelar"],
    specs:{ Chip:"Apple M3", RAM:"8 GB (hasta 24 GB)", Almacenamiento:"256 GB SSD", Pantalla:"13.6″ Liquid Retina", Batería:"Hasta 18 horas", Puertos:"2x USB-C, MagSafe 3", Peso:"1.24 kg", Teclado:"Magic Keyboard Touch ID" },
    desc:"El portátil más popular de Apple. Chip M3 con potencia silenciosa y hasta 18 horas de batería en diseño ultradelgado.",
    reseñas:[
      { fuente:"Applesfera",  nota:9.5, texto:"El portátil perfecto para la mayoría. Potente, silencioso y con batería para todo el día.", fecha:"Mar 2024" },
      { fuente:"Xataka",      nota:9.1, texto:"El M3 supera al M2 en multitarea. La pantalla Liquid Retina sigue siendo excelente.", fecha:"Mar 2024" },
      { fuente:"Computer Hoy",nota:8.8, texto:"Para usuarios creativos o profesionales que buscan fiabilidad, es la mejor opción.", fecha:"Abr 2024" },
    ],
    historial:[{m:"Ene",p:1399},{m:"Feb",p:1360},{m:"Mar",p:1320},{m:"Abr",p:1299},{m:"May",p:1275},{m:"Jun",p:1249}],
    precios:{ apple:1299, mediamarkt:1279, pccomp:1259, amazon:1249, elcorte:1299, fnac:1289, worten:1275, istore:1299 },
  },
  {
    id:3, nombre:"iPad Pro 11″ M4", cat:"ipad", emoji:"⬛", rating:4.9, tag:"Pro",
    fotos:["#1a1a1a","#2d2d2d","#404040","#555555"],
    fotoLabels:["Negro Espacial","Plata","Gris","Titanio"],
    specs:{ Chip:"Apple M4", Pantalla:"11″ Ultra Retina XDR OLED", "Apple Pencil Pro":"Compatible", Teclado:"Magic Keyboard", Batería:"Hasta 10h", Almacenamiento:"256 GB", Conectividad:"Wi-Fi 6E + 5G", Peso:"444 g" },
    desc:"El iPad más delgado jamás creado. Con chip M4 y pantalla OLED Ultra Retina XDR, es la herramienta definitiva para creativos.",
    reseñas:[
      { fuente:"Applesfera", nota:9.4, texto:"Pantalla OLED increíble. Si necesitas el iPad más potente, este es sin duda.", fecha:"May 2024" },
      { fuente:"Xataka",     nota:9.0, texto:"El M4 es potencia de sobra. La pantalla marca un antes y después en tablets.", fecha:"May 2024" },
      { fuente:"20minutos",  nota:8.7, texto:"Caro pero impresionante. Para diseñadores y editores, sin rival.", fecha:"Jun 2024" },
    ],
    historial:[{m:"Ene",p:1149},{m:"Feb",p:1129},{m:"Mar",p:1099},{m:"Abr",p:1099},{m:"May",p:1079},{m:"Jun",p:1059}],
    precios:{ apple:1099, mediamarkt:1089, pccomp:1069, amazon:1059, elcorte:1099, fnac:1079, worten:1089, istore:1099 },
  },
  {
    id:4, nombre:"Apple Watch Series 10", cat:"watch", emoji:"⌚", rating:4.7, tag:"Novedad",
    fotos:["#1c1c1e","#2c1a1a","#1a2c1a","#1a1a2c"],
    fotoLabels:["Aluminio Negro","Rojo Product(RED)","Verde","Azul"],
    specs:{ Pantalla:"46mm Always-On OLED", Sensor:"Temperatura, ECG, SpO2", "Detección caídas":"Sí", GPS:"Sí", "Resistencia agua":"50m", Batería:"Hasta 18h", "watchOS":"11", Correa:"Sport Band" },
    desc:"El Apple Watch más avanzado con pantalla un 30% más grande, detección de apnea del sueño y ECG de segunda generación.",
    reseñas:[
      { fuente:"Andro4all", nota:8.8, texto:"El mejor smartwatch del mercado. La detección de apnea del sueño es un hito.", fecha:"Sep 2024" },
      { fuente:"Xataka",    nota:8.5, texto:"Pantalla más grande y brillante. Si tienes el S9, la actualización no es urgente.", fecha:"Sep 2024" },
      { fuente:"El País",   nota:8.6, texto:"Salud y deporte en un solo dispositivo. Ecosistema Apple inigualable.", fecha:"Oct 2024" },
    ],
    historial:[{m:"Ene",p:499},{m:"Feb",p:489},{m:"Mar",p:469},{m:"Abr",p:449},{m:"May",p:439},{m:"Jun",p:419}],
    precios:{ apple:449, mediamarkt:439, pccomp:429, amazon:419, elcorte:449, fnac:435, worten:439, istore:449 },
  },
  {
    id:5, nombre:"AirPods Pro 2", cat:"airpods", emoji:"🎧", rating:4.8, tag:"Más vendido",
    fotos:["#e8e8e8","#d0d0d0","#b8b8b8","#a0a0a0"],
    fotoLabels:["Blanco Estelar","Blanco","Plata","Estuche USB-C"],
    specs:{ ANC:"Cancelación activa H2", Chip:"H2", Batería:"6h + 24h estuche", "Carga inalámbrica":"MagSafe + Qi", Resistencia:"IPX4", Audio:"Dolby Atmos espacial", Control:"Gesto pellizco", Transparencia:"Modo adaptativo" },
    desc:"Los mejores auriculares inalámbricos de Apple con cancelación de ruido de siguiente nivel y audio espacial personalizado.",
    reseñas:[
      { fuente:"Xataka",     nota:9.3, texto:"Los mejores ANC del mercado. El audio espacial personalizado es impresionante.", fecha:"Ago 2023" },
      { fuente:"Applesfera", nota:9.1, texto:"Si tienes iPhone, son los auriculares a comprar. Sin discusión.", fecha:"Sep 2023" },
      { fuente:"Rtve.es",    nota:8.9, texto:"Calidad de sonido excepcional y ANC que aísla de verdad el ruido exterior.", fecha:"Oct 2023" },
    ],
    historial:[{m:"Ene",p:299},{m:"Feb",p:289},{m:"Mar",p:279},{m:"Abr",p:269},{m:"May",p:259},{m:"Jun",p:249}],
    precios:{ apple:279, mediamarkt:269, pccomp:259, amazon:249, elcorte:279, fnac:265, worten:269, istore:279 },
  },
  {
    id:6, nombre:"iPhone 15 128 GB", cat:"iphone", emoji:"📱", rating:4.7, tag:"Oferta",
    fotos:["#2d4a22","#1a3a5c","#5c1a3a","#4a3a1a"],
    fotoLabels:["Verde","Azul","Rosa","Amarillo"],
    specs:{ Pantalla:"6.1″ Super Retina XDR", Chip:"A16 Bionic", Cámara:"48MP + 12MP", Batería:"Hasta 20h vídeo", Almacenamiento:"128 GB", USB:"USB-C", "5G":"Sí", Peso:"171 g" },
    desc:"iPhone 15 con chip A16 Bionic y primer iPhone con USB-C. Cámara de 48MP con modo retrato mejorado.",
    reseñas:[
      { fuente:"Xataka",      nota:8.7, texto:"La transición a USB-C es bienvenida. El A16 sigue siendo muy potente en 2024.", fecha:"Sep 2023" },
      { fuente:"Hardzone",    nota:8.5, texto:"Buena actualización con USB-C y cámara mejorada. Precio muy competitivo ahora.", fecha:"Oct 2023" },
      { fuente:"Tecnoxplora", nota:8.6, texto:"Para quien quiere iPhone sin gastar de más, el 15 es la mejor relación calidad-precio.", fecha:"Ene 2024" },
    ],
    historial:[{m:"Ene",p:979},{m:"Feb",p:949},{m:"Mar",p:929},{m:"Abr",p:899},{m:"May",p:869},{m:"Jun",p:829}],
    precios:{ apple:879, mediamarkt:849, pccomp:839, amazon:829, elcorte:879, fnac:859, worten:849, istore:879 },
  },
  {
    id:7, nombre:"MacBook Pro 14″ M4", cat:"mac", emoji:"💻", rating:4.9, tag:"Pro",
    fotos:["#1c1c1e","#2c2c2e","#3a3a3c","#48484a"],
    fotoLabels:["Negro Espacial","Gris Espacial","Plata","Plata Pro"],
    specs:{ Chip:"Apple M4 Pro", RAM:"24 GB unificada", Pantalla:"14.2″ Liquid Retina XDR", Batería:"Hasta 24h", Puertos:"3x USB-C, HDMI, SD, MagSafe", "ProRes":"Vídeo ProRes", Peso:"1.62 kg", GPU:"20 núcleos" },
    desc:"El MacBook Pro definitivo para profesionales. Chip M4 Pro con hasta 24 horas de batería y pantalla XDR de referencia.",
    reseñas:[
      { fuente:"Applesfera",   nota:9.7, texto:"El portátil más potente del mercado para profesionales creativos. Sin ninguna duda.", fecha:"Nov 2024" },
      { fuente:"Xataka",       nota:9.4, texto:"M4 Pro es una bestia. Edita vídeo 8K ProRes sin pestañear. La batería es un récord.", fecha:"Nov 2024" },
      { fuente:"The Verge ES", nota:9.2, texto:"Si tu trabajo depende del rendimiento, este MacBook Pro es la inversión correcta.", fecha:"Dic 2024" },
    ],
    historial:[{m:"Ene",p:2149},{m:"Feb",p:2099},{m:"Mar",p:2049},{m:"Abr",p:1999},{m:"May",p:1969},{m:"Jun",p:1939}],
    precios:{ apple:1999, mediamarkt:1979, pccomp:1949, amazon:1939, elcorte:1999, fnac:1969, worten:1979, istore:1999 },
  },
  {
    id:8, nombre:"Magic Keyboard Touch ID", cat:"accesorios", emoji:"⌨️", rating:4.6, tag:"",
    fotos:["#e8e8e8","#1c1c1e","#c8b89a","#a8c4d4"],
    fotoLabels:["Plata","Negro Espacial","Oro","Azul Cielo"],
    specs:{ Conexión:"Bluetooth 5.0 + USB-C", "Touch ID":"Sí", Layout:"Español", Batería:"Hasta 1 mes", Teclas:"Perfil bajo tijera", Compatibilidad:"Mac, iPad", Tamaño:"Compacto", Peso:"239 g" },
    desc:"El teclado inalámbrico de Apple con Touch ID integrado para layout español. Batería de larga duración.",
    reseñas:[
      { fuente:"Applesfera", nota:8.8, texto:"El mejor teclado para Mac. Touch ID es un lujo que no querrás soltar.", fecha:"2023" },
      { fuente:"Xataka",    nota:8.4, texto:"Calidad de escritura premium. Touch ID integrado funciona a la perfección.", fecha:"2023" },
      { fuente:"Hardzone",  nota:8.2, texto:"Precio elevado para un teclado, pero la experiencia justifica la inversión.", fecha:"2023" },
    ],
    historial:[{m:"Ene",p:119},{m:"Feb",p:115},{m:"Mar",p:109},{m:"Abr",p:105},{m:"May",p:99},{m:"Jun",p:89}],
    precios:{ apple:109, mediamarkt:99, pccomp:95, amazon:89, elcorte:109, fnac:99, worten:99, istore:109 },
  },
  {
    id:9, nombre:"Apple Vision Pro", cat:"accesorios", emoji:"🥽", rating:4.5, tag:"Exclusivo",
    fotos:["#1a1a2e","#0d0d1a","#2a1a2e","#1a2a1a"],
    fotoLabels:["Gris Espacial","Negro","Morado","Verde Bosque"],
    specs:{ Chip:"M2 + R1", Pantalla:"Micro-OLED 23M píxeles", "visionOS":"2", Almacenamiento:"256 GB", Audio:"Spatial Audio", Conectividad:"Wi-Fi 6E + Bluetooth 5.3", Batería:"2h exterior", Peso:"600–650 g" },
    desc:"El primer ordenador espacial de Apple. Realidad mixta con pantallas micro-OLED de 23 millones de píxeles.",
    reseñas:[
      { fuente:"El País Tech", nota:8.5, texto:"Un producto del futuro. La experiencia es impresionante aunque el precio sigue siendo muy alto.", fecha:"Feb 2024" },
      { fuente:"Xataka",       nota:8.0, texto:"Wow técnico absoluto. Los casos de uso cotidiano aún están por definirse.", fecha:"Mar 2024" },
      { fuente:"Applesfera",   nota:8.8, texto:"Una revolución tecnológica que aún necesita madurar en contenido y apps.", fecha:"Abr 2024" },
    ],
    historial:[{m:"Ene",p:3999},{m:"Feb",p:3999},{m:"Mar",p:3899},{m:"Abr",p:3899},{m:"May",p:3899},{m:"Jun",p:3899}],
    precios:{ apple:3999, amazon:3899, elcorte:3999, istore:3999 },
  },
  {
    id:10, nombre:"iPad mini 7", cat:"ipad", emoji:"⬛", rating:4.7, tag:"Novedad",
    fotos:["#1c1c1e","#c8b89a","#1a3a5c","#5c1a3a"],
    fotoLabels:["Negro Espacial","Starlight","Azul","Púrpura"],
    specs:{ Pantalla:"8.3″ Liquid Retina", Chip:"Apple A17 Pro", "Apple Pencil Pro":"Compatible", Batería:"Hasta 10h", Almacenamiento:"128 GB", Conectividad:"Wi-Fi 6E + 5G", Peso:"293 g", USB:"USB-C" },
    desc:"El iPad mini más potente. Chip A17 Pro con soporte para Apple Intelligence y compatible con Apple Pencil Pro por primera vez.",
    reseñas:[
      { fuente:"Applesfera",  nota:9.0, texto:"El iPad mini definitivo. A17 Pro trae Apple Intelligence y es un salto generacional.", fecha:"Oct 2024" },
      { fuente:"Xataka",      nota:8.7, texto:"Perfecto para leer, dibujar y trabajar en movilidad. El mejor mini hasta la fecha.", fecha:"Oct 2024" },
      { fuente:"Hipertextual",nota:8.5, texto:"Si quieres un iPad compacto y potente, el mini 7 no tiene rival.", fecha:"Nov 2024" },
    ],
    historial:[{m:"Ene",p:619},{m:"Feb",p:599},{m:"Mar",p:579},{m:"Abr",p:569},{m:"May",p:549},{m:"Jun",p:529}],
    precios:{ apple:569, mediamarkt:549, pccomp:539, amazon:529, elcorte:569, fnac:549, worten:549, istore:569 },
  },
  {
    id:11, nombre:"AirPods 4", cat:"airpods", emoji:"🎧", rating:4.6, tag:"Novedad",
    fotos:["#e8e8e8","#d0d0d0","#b8b8b8","#f0f0f0"],
    fotoLabels:["Blanco","Blanco Mate","Plata","Estuche MagSafe"],
    specs:{ ANC:"Cancelación activa (modelo ANC)", Chip:"H2", Batería:"5h + 30h estuche", Resistencia:"IP54", Audio:"Dolby Atmos", Fit:"Abierto sin almohadillas", Control:"Gesto pellizco", "Carga inalámbrica":"MagSafe" },
    desc:"Los nuevos AirPods con diseño rediseñado sin almohadillas. Audio de alta fidelidad con opción de cancelación activa de ruido.",
    reseñas:[
      { fuente:"Xataka",      nota:8.6, texto:"El nuevo diseño es más cómodo. El salto en calidad de audio respecto a gen 3 es notable.", fecha:"Sep 2024" },
      { fuente:"Applesfera",  nota:8.4, texto:"Para quien no quiere auriculares de canal, los AirPods 4 son la referencia.", fecha:"Sep 2024" },
      { fuente:"Engadget ES", nota:8.3, texto:"Mejora real en sonido y ajuste. La versión con ANC vale la pena el extra.", fecha:"Oct 2024" },
    ],
    historial:[{m:"Ene",p:179},{m:"Feb",p:169},{m:"Mar",p:159},{m:"Abr",p:149},{m:"May",p:139},{m:"Jun",p:129}],
    precios:{ apple:149, mediamarkt:139, pccomp:135, amazon:129, elcorte:149, fnac:139, worten:139, istore:149 },
  },
  {
    id:12, nombre:"Apple Watch Ultra 2", cat:"watch", emoji:"⌚", rating:4.9, tag:"Ultra",
    fotos:["#c8a87a","#1c1c1e","#4a6741","#2a4a6a"],
    fotoLabels:["Titanio Natural","Titanio Negro","Titanio Verde","Titanio Azul"],
    specs:{ Pantalla:"49mm Always-On OLED", GPS:"L1+L5 doble frecuencia", Profundidad:"100m", Batería:"Hasta 60h", Altavoz:"86 dB", Chip:"S9 SiP", Temperatura:"Sensor agua fría/caliente", Peso:"61 g" },
    desc:"El Apple Watch más resistente. Diseño en titanio con GPS de doble frecuencia y hasta 60 horas de batería para expediciones extremas.",
    reseñas:[
      { fuente:"Xataka",      nota:9.3, texto:"Para deportistas y aventureros es insuperable. GPS de doble frecuencia en montaña es un plus enorme.", fecha:"Sep 2023" },
      { fuente:"Applesfera",  nota:9.5, texto:"El smartwatch más completo del mercado. Batería de 60h es un récord para Apple.", fecha:"Sep 2023" },
      { fuente:"Runedia.com", nota:9.4, texto:"Para trail running y triatlón es la referencia. Datos de entrenamiento muy precisos.", fecha:"Oct 2023" },
    ],
    historial:[{m:"Ene",p:999},{m:"Feb",p:979},{m:"Mar",p:949},{m:"Abr",p:929},{m:"May",p:899},{m:"Jun",p:869}],
    precios:{ apple:899, mediamarkt:879, pccomp:859, amazon:849, elcorte:899, fnac:869, worten:879, istore:899 },
  },
];

export const BU_INICIALES = [
  { id:"bu1", productoId:1, precio:820, estado:"Excelente", ciudad:"Madrid",    fotos:[], descripcion:"Comprado hace 6 meses, sin rayones. Con caja y accesorios originales.", vendedor:"Carlos M.", fecha:"15/05/2025" },
  { id:"bu2", productoId:2, precio:950, estado:"Muy bueno", ciudad:"Barcelona", fotos:[], descripcion:"MacBook en perfecto estado. Batería al 94%. Funda de regalo.",           vendedor:"Ana G.",    fecha:"10/05/2025" },
  { id:"bu3", productoId:5, precio:170, estado:"Bueno",     ciudad:"Valencia",  fotos:[], descripcion:"AirPods Pro con estuche MagSafe. Autonomía perfecta.",                   vendedor:"Luis P.",   fecha:"18/05/2025" },
  { id:"bu4", productoId:4, precio:280, estado:"Excelente", ciudad:"Sevilla",   fotos:[], descripcion:"Usado solo 3 meses. Correa Sport Loop incluida.",                        vendedor:"María R.",  fecha:"12/05/2025" },
  { id:"bu5", productoId:6, precio:620, estado:"Muy bueno", ciudad:"Bilbao",    fotos:[], descripcion:"iPhone 15 sin marcas. Face ID perfecto. Batería 89%.",                   vendedor:"Iñaki Z.", fecha:"05/05/2025" },
];
